CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE business_partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    tax_number VARCHAR(50),
    email VARCHAR(255),
    phone VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (organization_id, code),
    UNIQUE (organization_id, id)
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    item_type VARCHAR(30) NOT NULL DEFAULT 'MATERIAL' CHECK (item_type IN ('MATERIAL', 'COMPONENT', 'PRODUCT')),
    base_uom VARCHAR(20) NOT NULL,
    tracking_type VARCHAR(20) NOT NULL DEFAULT 'NONE' CHECK (tracking_type IN ('NONE', 'LOT', 'SERIAL')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (organization_id, sku),
    UNIQUE (organization_id, id)
);

CREATE TABLE item_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    item_id BIGINT NOT NULL,
    revision_code VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ACTIVE', 'OBSOLETE')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (organization_id, item_id) REFERENCES items(organization_id, id),
    UNIQUE (item_id, revision_code),
    UNIQUE (organization_id, id)
);

CREATE TABLE boms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    product_revision_id BIGINT NOT NULL,
    version INTEGER NOT NULL CHECK (version > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'APPROVED', 'OBSOLETE')),
    output_quantity NUMERIC(18,6) NOT NULL CHECK (output_quantity > 0 AND output_quantity <> 'NaN'::numeric),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (organization_id, product_revision_id) REFERENCES item_revisions(organization_id, id),
    UNIQUE (product_revision_id, version),
    UNIQUE (organization_id, id, product_revision_id),
    UNIQUE (organization_id, id)
);

CREATE TABLE bom_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    bom_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL CHECK (line_no > 0),
    component_revision_id BIGINT NOT NULL,
    quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0 AND quantity <> 'NaN'::numeric),
    FOREIGN KEY (organization_id, bom_id) REFERENCES boms(organization_id, id),
    FOREIGN KEY (organization_id, component_revision_id) REFERENCES item_revisions(organization_id, id),
    UNIQUE (bom_id, line_no),
    UNIQUE (organization_id, id, bom_id, component_revision_id),
    UNIQUE (organization_id, id)
);

CREATE TABLE inventory_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    parent_location_id BIGINT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    location_type VARCHAR(30) NOT NULL DEFAULT 'WAREHOUSE' CHECK (location_type IN ('WAREHOUSE', 'BIN', 'PRODUCTION', 'QUARANTINE', 'DAMAGED', 'TRANSIT')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (organization_id, parent_location_id) REFERENCES inventory_locations(organization_id, id),
    CHECK (parent_location_id IS NULL OR parent_location_id <> id),
    UNIQUE (organization_id, code),
    UNIQUE (organization_id, id)
);

CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    movement_type VARCHAR(40) NOT NULL DEFAULT 'RECEIPT' CHECK (movement_type IN ('RECEIPT', 'TRANSFER', 'PRODUCTION_CONSUMPTION', 'PRODUCTION_OUTPUT', 'SHIPMENT', 'ADJUSTMENT')),
    reference VARCHAR(100),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (organization_id, id)
);

CREATE TABLE inventory_movement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    movement_id BIGINT NOT NULL,
    item_revision_id BIGINT NOT NULL,
    from_location_id BIGINT,
    to_location_id BIGINT,
    quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0 AND quantity <> 'NaN'::numeric),
    FOREIGN KEY (organization_id, movement_id) REFERENCES inventory_movements(organization_id, id),
    FOREIGN KEY (organization_id, item_revision_id) REFERENCES item_revisions(organization_id, id),
    FOREIGN KEY (organization_id, from_location_id) REFERENCES inventory_locations(organization_id, id),
    FOREIGN KEY (organization_id, to_location_id) REFERENCES inventory_locations(organization_id, id),
    CHECK (from_location_id IS NOT NULL OR to_location_id IS NOT NULL),
    CHECK (from_location_id IS DISTINCT FROM to_location_id),
    UNIQUE (organization_id, id)
);

CREATE TABLE sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    order_number VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'CONFIRMED', 'RESERVED', 'PARTIALLY_SHIPPED', 'SHIPPED', 'CANCELLED')),
    currency_code CHAR(3) NOT NULL CHECK (currency_code ~ '^[A-Z]{3}$'),
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    required_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (organization_id, customer_id) REFERENCES business_partners(organization_id, id),
    UNIQUE (organization_id, order_number),
    UNIQUE (organization_id, id)
);

CREATE TABLE sales_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    sales_order_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL CHECK (line_no > 0),
    item_revision_id BIGINT NOT NULL,
    quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0 AND quantity <> 'NaN'::numeric),
    unit_price NUMERIC(18,4) CHECK (unit_price >= 0 AND unit_price <> 'NaN'::numeric),
    FOREIGN KEY (organization_id, sales_order_id) REFERENCES sales_orders(organization_id, id),
    FOREIGN KEY (organization_id, item_revision_id) REFERENCES item_revisions(organization_id, id),
    UNIQUE (sales_order_id, line_no),
    UNIQUE (organization_id, id, item_revision_id),
    UNIQUE (organization_id, id)
);

CREATE TABLE production_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    production_order_number VARCHAR(50) NOT NULL,
    product_revision_id BIGINT NOT NULL,
    bom_id BIGINT NOT NULL,
    source_sales_order_line_id BIGINT,
    quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0 AND quantity <> 'NaN'::numeric),
    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'APPROVED', 'RELEASED', 'IN_PRODUCTION', 'COMPLETED', 'CANCELLED')),
    planned_start_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (organization_id, product_revision_id) REFERENCES item_revisions(organization_id, id),
    FOREIGN KEY (organization_id, bom_id, product_revision_id) REFERENCES boms(organization_id, id, product_revision_id),
    FOREIGN KEY (organization_id, source_sales_order_line_id, product_revision_id) REFERENCES sales_order_lines(organization_id, id, item_revision_id),
    UNIQUE (organization_id, production_order_number),
    UNIQUE (organization_id, id, bom_id),
    UNIQUE (organization_id, id)
);

CREATE TABLE production_order_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    production_order_id BIGINT NOT NULL,
    bom_id BIGINT NOT NULL,
    bom_line_id BIGINT NOT NULL,
    component_revision_id BIGINT NOT NULL,
    required_quantity NUMERIC(18,6) NOT NULL CHECK (required_quantity > 0 AND required_quantity <> 'NaN'::numeric),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (organization_id, production_order_id, bom_id) REFERENCES production_orders(organization_id, id, bom_id),
    FOREIGN KEY (organization_id, bom_line_id, bom_id, component_revision_id) REFERENCES bom_lines(organization_id, id, bom_id, component_revision_id),
    UNIQUE (production_order_id, bom_line_id),
    UNIQUE (organization_id, id, component_revision_id),
    UNIQUE (organization_id, id)
);

CREATE TABLE stock_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    item_revision_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    sales_order_line_id BIGINT,
    production_order_material_id BIGINT,
    quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0 AND quantity <> 'NaN'::numeric),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CONSUMED', 'RELEASED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (organization_id, item_revision_id) REFERENCES item_revisions(organization_id, id),
    FOREIGN KEY (organization_id, location_id) REFERENCES inventory_locations(organization_id, id),
    FOREIGN KEY (organization_id, sales_order_line_id, item_revision_id) REFERENCES sales_order_lines(organization_id, id, item_revision_id),
    FOREIGN KEY (organization_id, production_order_material_id, item_revision_id) REFERENCES production_order_materials(organization_id, id, component_revision_id),
    CHECK (num_nonnulls(sales_order_line_id, production_order_material_id) = 1),
    UNIQUE (organization_id, id)
);

-- FK lookup and stock calculation indexes (unique constraints already index document lines).
CREATE INDEX ix_revisions_org_item ON item_revisions(organization_id, item_id);
CREATE INDEX ix_boms_org_product ON boms(organization_id, product_revision_id);
CREATE INDEX ix_bom_components ON bom_lines(organization_id, component_revision_id);
CREATE INDEX ix_location_parent ON inventory_locations(organization_id, parent_location_id);
CREATE INDEX ix_movements_occurred ON inventory_movements(organization_id, occurred_at);
CREATE INDEX ix_movement_lines_document ON inventory_movement_lines(organization_id, movement_id);
CREATE INDEX ix_stock_in ON inventory_movement_lines(organization_id, item_revision_id, to_location_id);
CREATE INDEX ix_stock_out ON inventory_movement_lines(organization_id, item_revision_id, from_location_id);
CREATE INDEX ix_sales_customer ON sales_orders(organization_id, customer_id);
CREATE INDEX ix_sales_revision ON sales_order_lines(organization_id, item_revision_id);
CREATE INDEX ix_production_source ON production_orders(organization_id, source_sales_order_line_id);
CREATE INDEX ix_production_bom ON production_orders(organization_id, bom_id);
CREATE INDEX ix_material_bom_line ON production_order_materials(organization_id, bom_line_id);
CREATE INDEX ix_reservations_stock ON stock_reservations(organization_id, item_revision_id, location_id) WHERE status = 'ACTIVE';
CREATE INDEX ix_reservations_sales ON stock_reservations(organization_id, sales_order_line_id);
CREATE INDEX ix_reservations_material ON stock_reservations(organization_id, production_order_material_id);

CREATE VIEW inventory_availability AS
WITH deltas AS (
    SELECT organization_id, item_revision_id, to_location_id AS location_id, quantity
    FROM inventory_movement_lines WHERE to_location_id IS NOT NULL
    UNION ALL
    SELECT organization_id, item_revision_id, from_location_id, -quantity
    FROM inventory_movement_lines WHERE from_location_id IS NOT NULL
), stock AS (
    SELECT organization_id, item_revision_id, location_id, sum(quantity) AS on_hand_quantity
    FROM deltas GROUP BY organization_id, item_revision_id, location_id
), reserved AS (
    SELECT organization_id, item_revision_id, location_id, sum(quantity) AS reserved_quantity
    FROM stock_reservations WHERE status = 'ACTIVE'
    GROUP BY organization_id, item_revision_id, location_id
)
SELECT coalesce(s.organization_id, r.organization_id) AS organization_id,
       coalesce(s.item_revision_id, r.item_revision_id) AS item_revision_id,
       coalesce(s.location_id, r.location_id) AS location_id,
       coalesce(s.on_hand_quantity, 0) AS on_hand_quantity,
       coalesce(r.reserved_quantity, 0) AS reserved_quantity,
       coalesce(s.on_hand_quantity, 0) - coalesce(r.reserved_quantity, 0) AS available_quantity
FROM stock s FULL JOIN reserved r USING (organization_id, item_revision_id, location_id);

CREATE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE FUNCTION reject_history_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION '% is append-only; create a correcting record', TG_TABLE_NAME; END $$;

-- All stock writes serialize per organization for this small V1.
-- READ COMMITTED ensures checks after waiting see the preceding committed stock writes.
CREATE FUNCTION lock_stock() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('transaction_isolation') <> 'read committed' THEN
        RAISE EXCEPTION 'Stock writes require READ COMMITTED isolation';
    END IF;
    PERFORM pg_advisory_xact_lock(NEW.organization_id);
    RETURN NEW;
END $$;

CREATE FUNCTION validate_stock() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE balance numeric; reserved_total numeric; demand numeric;
BEGIN
    IF TG_TABLE_NAME = 'stock_reservations' THEN
        IF TG_OP = 'UPDATE' THEN
            IF (NEW.organization_id, NEW.item_revision_id, NEW.location_id,
                NEW.sales_order_line_id, NEW.production_order_material_id, NEW.quantity)
               IS DISTINCT FROM
               (OLD.organization_id, OLD.item_revision_id, OLD.location_id,
                OLD.sales_order_line_id, OLD.production_order_material_id, OLD.quantity) THEN
                RAISE EXCEPTION 'Reservation allocation is immutable; release and create a new reservation';
            END IF;
            IF OLD.status <> 'ACTIVE' AND NEW.status <> OLD.status THEN
                RAISE EXCEPTION 'A terminal reservation cannot change status';
            END IF;
        END IF;
        IF NEW.status = 'ACTIVE' THEN
            IF NOT EXISTS (
                SELECT 1 FROM inventory_locations WHERE id = NEW.location_id
                AND is_active AND location_type IN ('WAREHOUSE', 'BIN', 'PRODUCTION')
            ) THEN RAISE EXCEPTION 'Stock location is not reservable'; END IF;
            SELECT available_quantity INTO balance FROM inventory_availability
            WHERE organization_id = NEW.organization_id AND item_revision_id = NEW.item_revision_id
              AND location_id = NEW.location_id;
            IF coalesce(balance, 0) < 0 THEN RAISE EXCEPTION 'Insufficient available stock'; END IF;
            IF NEW.sales_order_line_id IS NOT NULL THEN
                SELECT quantity INTO demand FROM sales_order_lines WHERE id = NEW.sales_order_line_id;
                SELECT sum(quantity) INTO reserved_total FROM stock_reservations
                WHERE sales_order_line_id = NEW.sales_order_line_id AND status IN ('ACTIVE', 'CONSUMED');
            ELSE
                SELECT required_quantity INTO demand FROM production_order_materials
                WHERE id = NEW.production_order_material_id;
                SELECT sum(quantity) INTO reserved_total FROM stock_reservations
                WHERE production_order_material_id = NEW.production_order_material_id AND status IN ('ACTIVE', 'CONSUMED');
            END IF;
            IF reserved_total > demand THEN RAISE EXCEPTION 'Reservation exceeds demand'; END IF;
        END IF;
    ELSIF NEW.from_location_id IS NOT NULL THEN
        SELECT available_quantity INTO balance FROM inventory_availability
        WHERE organization_id = NEW.organization_id AND item_revision_id = NEW.item_revision_id
          AND location_id = NEW.from_location_id;
        IF coalesce(balance, 0) < 0 THEN RAISE EXCEPTION 'Movement would consume unavailable stock'; END IF;
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER lock_movement_stock BEFORE INSERT ON inventory_movement_lines
FOR EACH ROW EXECUTE FUNCTION lock_stock();
CREATE TRIGGER check_movement_stock AFTER INSERT ON inventory_movement_lines
FOR EACH ROW EXECUTE FUNCTION validate_stock();
CREATE TRIGGER lock_reservation_stock BEFORE INSERT OR UPDATE ON stock_reservations
FOR EACH ROW EXECUTE FUNCTION lock_stock();
CREATE TRIGGER check_reservation_stock AFTER INSERT OR UPDATE ON stock_reservations
FOR EACH ROW EXECUTE FUNCTION validate_stock();
CREATE TRIGGER preserve_reservations BEFORE DELETE ON stock_reservations
FOR EACH ROW EXECUTE FUNCTION reject_history_change();

CREATE FUNCTION protect_bom() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE parent_status text;
BEGIN
    IF TG_TABLE_NAME = 'bom_lines' THEN
        IF TG_OP = 'UPDATE' AND (NEW.bom_id, NEW.organization_id) IS DISTINCT FROM (OLD.bom_id, OLD.organization_id) THEN
            RAISE EXCEPTION 'BOM lines cannot move between BOMs';
        END IF;
        SELECT status INTO parent_status FROM boms
        WHERE id = CASE WHEN TG_OP = 'DELETE' THEN OLD.bom_id ELSE NEW.bom_id END FOR UPDATE;
        IF parent_status <> 'DRAFT' THEN RAISE EXCEPTION 'Only draft BOM lines can change'; END IF;
    ELSE
        IF OLD.status <> 'DRAFT' THEN
            IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Approved BOM history cannot be deleted'; END IF;
            IF (NEW.organization_id, NEW.product_revision_id, NEW.version, NEW.output_quantity)
               IS DISTINCT FROM (OLD.organization_id, OLD.product_revision_id, OLD.version, OLD.output_quantity)
               OR NEW.status NOT IN (OLD.status, 'OBSOLETE') THEN
                RAISE EXCEPTION 'Approved BOM recipe is immutable; create a new version';
            END IF;
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER protect_bom_header BEFORE UPDATE OR DELETE ON boms FOR EACH ROW EXECUTE FUNCTION protect_bom();
CREATE TRIGGER protect_bom_lines BEFORE INSERT OR UPDATE OR DELETE ON bom_lines FOR EACH ROW EXECUTE FUNCTION protect_bom();

CREATE FUNCTION validate_production() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE recipe_status text; calculated numeric;
BEGIN
    IF TG_TABLE_NAME = 'production_orders' THEN
        SELECT status INTO recipe_status FROM boms WHERE id = NEW.bom_id FOR SHARE;
        IF recipe_status <> 'APPROVED' THEN RAISE EXCEPTION 'Production requires an approved exact BOM'; END IF;
    ELSE
        SELECT round(p.quantity * l.quantity / b.output_quantity, 6) INTO calculated
        FROM production_orders p JOIN boms b ON b.id = p.bom_id
        JOIN bom_lines l ON l.bom_id = b.id
        WHERE p.id = NEW.production_order_id AND l.id = NEW.bom_line_id;
        IF NEW.required_quantity IS DISTINCT FROM calculated THEN
            RAISE EXCEPTION 'Material requirement must equal production quantity * BOM line quantity / BOM output quantity';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER check_production_bom BEFORE INSERT ON production_orders FOR EACH ROW EXECUTE FUNCTION validate_production();
CREATE TRIGGER check_material_snapshot BEFORE INSERT ON production_order_materials FOR EACH ROW EXECUTE FUNCTION validate_production();
CREATE TRIGGER preserve_material_snapshot BEFORE UPDATE OR DELETE ON production_order_materials FOR EACH ROW EXECUTE FUNCTION reject_history_change();

CREATE FUNCTION protect_production_plan() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.organization_id, NEW.product_revision_id, NEW.bom_id, NEW.quantity, NEW.source_sales_order_line_id)
       IS DISTINCT FROM (OLD.organization_id, OLD.product_revision_id, OLD.bom_id, OLD.quantity, OLD.source_sales_order_line_id) THEN
        RAISE EXCEPTION 'Production recipe and quantity are immutable; cancel and create another order';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER preserve_production_plan BEFORE UPDATE ON production_orders FOR EACH ROW EXECUTE FUNCTION protect_production_plan();

CREATE TRIGGER touch_organizations BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER touch_business_partners BEFORE UPDATE ON business_partners FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER touch_items BEFORE UPDATE ON items FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER touch_stock_reservations BEFORE UPDATE ON stock_reservations FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER preserve_inventory_movements BEFORE UPDATE OR DELETE ON inventory_movements FOR EACH ROW EXECUTE FUNCTION reject_history_change();

CREATE TRIGGER preserve_inventory_movement_lines BEFORE UPDATE OR DELETE ON inventory_movement_lines FOR EACH ROW EXECUTE FUNCTION reject_history_change();

CREATE FUNCTION protect_revision() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.organization_id, NEW.item_id, NEW.revision_code) IS DISTINCT FROM (OLD.organization_id, OLD.item_id, OLD.revision_code) THEN
        RAISE EXCEPTION 'Revision identity is immutable; create a new revision';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER preserve_revision_identity BEFORE UPDATE ON item_revisions FOR EACH ROW EXECUTE FUNCTION protect_revision();
